export const OVERDUE_COUNT_RATE: { [propName: string]: string } = {
  '0': 'm_DPD0_count_rate',
  '1': 'q_DPD1_count_rate',
  '2': 'u_DPD2_count_rate',
  '3': 'y_DPD3_count_rate',
  // '4': 'a_c_DPD4_count_rate',
  // '5': 'a_g_DPD5_count_rate',
  '7': 'a_k_DPD7_count_rate',
  '15': 'a_o_DPD15_count_rate',
  '30': 'a_s_DPD30_count_rate',
  '60': 'a_w_DPD60_count_rate',
  '60+': 'b_a_DPD60+_count_rate',
};
export const OVERDUE_AMOUNT_RATE: { [propName: string]: string } = {
  '0': 'n_DPD0_amount_rate',
  '1': 'r_DPD1_amount_rate',
  '2': 'v_DPD2_amount_rate',
  '3': 'z_DPD3_amount_rate',
  // '4': 'a_d_DPD4_amount_rate',
  // '5': 'a_h_DPD5_amount_rate',
  '7': 'a_l_DPD7_amount_rate',
  '15': 'a_p_DPD15_amount_rate',
  '30': 'a_t_DPD30_amount_rate',
  '60': 'a_x_DPD60_amount_rate',
  '60+': 'b_b_DPD60+_amount_rate',
};
export const OVERDUE_COUNT: { [propName: string]: string } = {
  '0': 'k_DPD0_count',
  '1': 'o_DPD1_count',
  '2': 's_DPD2_count',
  '3': 'w_DPD3_count',
  // '4': 'a_a_DPD4_count',
  // '5': 'a_e_DPD5_count',
  '7': 'a_i_DPD7_count',
  '15': 'a_m_DPD15_count',
  '30': 'a_q_DPD30_count',
  '60': 'a_u_DPD60_count',
  '60+': 'a_y_DPD60+_count',
};
export const OVERDUE_AMOUNT: { [propName: string]: string } = {
  '0': 'l_DPD0_amount',
  '1': 'p_DPD1_amount',
  '2': 't_DPD2_amount',
  '3': 'x_DPD3_amount',
  // '4': 'a_b_DPD4_amount',
  // '5': 'a_f_DPD5_amount',
  '7': 'a_j_DPD7_amount',
  '15': 'a_n_DPD15_amount',
  '30': 'a_r_DPD30_amount',
  '60': 'a_v_DPD60_amount',
  '60+': 'a_z_DPD60+_amount',
};
