// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  id: 'id',
  a_date: '日期',
  b_template_count: 'b',
  c_template_count: 'c',
  d_template_count: 'd',
  e_template_count: 'e',
  f_template_count: 'f',
  g_template_count: 'g',
  h_template_count: 'h',
  i_template_count: 'i',
  j_template_count: 'j',
  k_template_count: 'k',
  l_template_count: 'l',
  m_template_count: 'm',
  n_template_count: 'n',
  o_template_count: 'o',
  p_template_count: 'p',
  q_template_count: 'q',
  r_template_count: 'r',
  s_template_count: 's',
  t_template_count: 't',
  u_template_count: 'u',
  v_template_count: 'v',
  w_template_count: 'w',
  x_template_count: 'x',
  y_template_count: 'y',
  z_template_count: 'z',
  a_a_template_count: 'aa',
  a_b_template_count: 'ab',
  a_c_template_count: 'ac',
  a_d_template_count: 'ad',
  a_e_template_count: 'ae',
  a_f_template_count: 'af',
  a_g_template_count: 'ag',
  a_h_template_count: 'ah',
  a_i_template_count: 'ai',
  a_j_template_count: 'aj',
  a_k_template_count: 'ak',

};

export const FieldIndex = {
  id: 'id',
  a_date: 'a_date',
  b_template_count: 'b_template_count',
  c_template_count: 'c_template_count',
  d_template_count: 'd_template_count',
  e_template_count: 'e_template_count',
  f_template_count: 'f_template_count',
  g_template_count: 'g_template_count',
  h_template_count: 'h_template_count',
  i_template_count: 'i_template_count',
  j_template_count: 'j_template_count',
  k_template_count: 'k_template_count',
  l_template_count: 'l_template_count',
  m_template_count: 'm_template_count',
  n_template_count: 'n_template_count',
  o_template_count: 'o_template_count',
  p_template_count: 'p_template_count',
  q_template_count: 'q_template_count',
  r_template_count: 'r_template_count',
  s_template_count: 's_template_count',
  t_template_count: 't_template_count',
  u_template_count: 'u_template_count',
  v_template_count: 'v_template_count',
  w_template_count: 'w_template_count',
  x_template_count: 'x_template_count',
  y_template_count: 'y_template_count',
  z_template_count: 'z_template_count',
  a_a_template_count: 'a_a_template_count',
  a_b_template_count: 'a_b_template_count',
  a_c_template_count: 'a_c_template_count',
  a_d_template_count: 'a_d_template_count',
  a_e_template_count: 'a_e_template_count',
  a_f_template_count: 'a_f_template_count',
  a_g_template_count: 'a_g_template_count',
  a_h_template_count: 'a_h_template_count',
  a_i_template_count: 'a_i_template_count',
  a_j_template_count: 'a_j_template_count',
  a_k_template_count: 'a_k_template_count',
  created_at: 'created_at',
  updated_at: 'updated_at',
};


