// @ts-ignore
/* eslint-disable */

import {
  FieldIndex as FieldIndex2,
  FieldLabels as FieldLabels2,
} from '@/pages/Loan/WaitingLoan/service';

export const FieldLabels = {
  id: 'id',
  a_borrow_id: 'borrow_id',
  b_repay_id: '用户',
  c_period_count: '分期期数',
  d_index: '展期序号',
  e_status: '状态',
  f_expect_repay_time: '应还款日',
  g_product_settlement_type: '结算方式*',
  h_expect_repay_total_amount: '剩余利息',
  j_before_paid_violate_fee: '展期前已支付违约金',
  k_before_paid_overdue_fee: '展期前已支付罚息',
  l_overdue_days: '在逾天数',
  m_days: '展期天数',
  n_before_expect_repay_time: '展前应还款日',
  o_after_expect_repay_time: '展后应还款日',
  p_extend_amount: '展期总额',
  q_extend_fee: '展期费',
  r_extend_violate_fee: '展期违约金',
  s_extend_overdue_fee: '展期罚息',
  t_period_id: '分期订单',
  u_user_id: '用户',
  v_admin_id: '管理员',
  w_repay_log_id: '支付流水id',
  x_period_index: '分期序号',
  created_at: '创建时间',
  updated_at: '更新时间',
  a_a_a_a_a_d_borrow: FieldLabels2,
};
export const FieldIndex = {
  id: 'id',
  a_borrow_id: 'a_borrow_id',
  b_repay_id: 'b_repay_id',
  c_period_count: 'c_period_count',
  d_index: 'd_index',
  e_status: 'e_status',
  f_expect_repay_time: 'f_expect_repay_time',
  g_product_settlement_type: 'g_product_settlement_type',
  h_expect_repay_total_amount: 'h_expect_repay_total_amount',
  j_before_paid_violate_fee: 'j_before_paid_violate_fee',
  k_before_paid_overdue_fee: 'k_before_paid_overdue_fee',
  l_overdue_days: 'l_overdue_days',
  m_days: 'm_days',
  n_before_expect_repay_time: 'n_before_expect_repay_time',
  o_after_expect_repay_time: 'o_after_expect_repay_time',
  p_extend_amount: 'p_extend_amount',
  q_extend_fee: 'q_extend_fee',
  r_extend_violate_fee: 'r_extend_violate_fee',
  s_extend_overdue_fee: 's_extend_overdue_fee',
  t_period_id: 't_period_id',
  u_user_id: 'u_user_id',
  v_admin_id: 'v_admin_id',
  w_repay_log_id: 'w_repay_log_id',
  x_period_index: 'x_period_index',
  created_at: 'created_at',
  updated_at: 'updated_at',
  a_a_a_a_a_d_borrow: FieldIndex2,
};
