// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  id: 'id',
  a_loan_date: '应还日期',
  b_product_id: '产品',
  c_loan_count: '放款单数',
  d_loan_period_count: '放款期数',
  e_settled_count: '结清数量',
  f_settled_period_count: '结清期数',
  g_loan_amount: '放款金额',
  h_repay_amount: '还款金额',
  i_extend_count: '展期数量',
  j_extend_amount: '展期金额',
  k_per_period_loan_amount: '每期放款金额',
  l_repay_amount_rate: '还款率',
  m_profit_amount_rate: '损益率',
  n_profit: '损益',
  o_period1_profit: 'P1',
  p_period2_profit: 'P2',
  q_period3_profit: 'P3',
  r_period4_profit: 'P4',
  s_period5_profit: 'P5',
  t_period6_profit: 'P6',
  u_period1_repay_count: 'P1',
  v_period2_repay_count: 'P2',
  w_period3_repay_count: 'P3',
  x_period4_repay_count: 'P4',
  y_period5_repay_count: 'P5',
  z_period6_repay_count: 'P6',
  a_a_per_period_expected_count: '期数',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex = {
  id: 'id',
  a_loan_date: 'a_loan_date',
  b_product_id: 'b_product_id',
  c_loan_count: 'c_loan_count',
  d_loan_period_count: 'd_loan_period_count',
  e_settled_count: 'e_settled_count',
  f_settled_period_count: 'f_settled_period_count',
  g_loan_amount: 'g_loan_amount',
  h_repay_amount: 'h_repay_amount',
  i_extend_count: 'i_extend_count',
  j_extend_amount: 'j_extend_amount',
  k_per_period_loan_amount: 'k_per_period_loan_amount',
  l_repay_amount_rate: 'l_repay_amount_rate',
  m_profit_amount_rate: 'm_profit_amount_rate',
  n_profit: 'n_profit',
  o_period1_profit: 'o_period1_profit',
  p_period2_profit: 'p_period2_profit',
  q_period3_profit: 'q_period3_profit',
  r_period4_profit: 'r_period4_profit',
  s_period5_profit: 's_period5_profit',
  t_period6_profit: 't_period6_profit',
  u_period1_repay_count: 'u_period1_repay_count',
  v_period2_repay_count: 'v_period2_repay_count',
  w_period3_repay_count: 'w_period3_repay_count',
  x_period4_repay_count: 'x_period4_repay_count',
  y_period5_repay_count: 'y_period5_repay_count',
  z_period6_repay_count: 'z_period6_repay_count',
  a_a_per_period_expected_count: 'a_a_per_period_expected_count',
  created_at: 'created_at',
  updated_at: 'updated_at',
};
