// @ts-ignore
/* eslint-disable */

import {
  FieldIndex as FieldIndex2,
  FieldLabels as FieldLabels2,
} from '@/pages/Loan/WaitingLoan/service';

export { getAdminV1ProductsEnum as getProductsEnum } from '@/services/ant-design-pro/BProduct';
export {
  getAdminV1MCLoanLogs as index,
  getAdminV1MCLoanLogsId as show,
} from '@/services/ant-design-pro/MCLoanLog';
export const FieldLabels = {
  a_borrow_id: 'borrow_id',
  b_loan_id: 'loan',
  c_admin_id: '管理员',
  d_loan_bank_id: 'loan',
  e_payment_channel: '最终支付渠道',
  f_method: '放款方式',
  g_type: '放款类型',
  h_status: '状态',
  i_receiver_name: '持卡人姓名',
  j_receiver_bankcard_number: '收款银行卡号',
  k_receiver_bankcard_name: '收款银行名称',
  l_receiver_bankcard_code: '收款银行编码',
  m_financial_system_code: '金融系统代码',
  o_loan_time: '打款时间',
  p_reference: 'reference',
  q_outer_sn: '上游流水号',
  r_amount: '金额',
  s_fee: 'fee',
  t_sync_code: '同步状态',
  u_sync_message: '同步消息',
  v_sync_raw: '同步原始报文',
  w_callback_code: '异步状态',
  x_callback_message: '异步消息',
  y_callback_raw: '异步原始报文',
  z_remark: '审核备注',
  a_a_certificate: '放款凭证',
  a_b_index: '放款次数',
  created_at: '创建时间',
  updated_at: '更新时间',
  a_a_a_a_a_d_borrow: FieldLabels2,
};
export const FieldIndex = {
  a_borrow_id: 'a_borrow_id',
  b_loan_id: 'b_loan_id',
  c_admin_id: 'c_admin_id',
  d_loan_bank_id: 'd_loan_bank_id',
  e_payment_channel: 'e_payment_channel',
  f_method: 'f_method',
  g_type: 'g_type',
  h_status: 'h_status',
  i_receiver_name: 'i_receiver_name',
  j_receiver_bankcard_number: 'j_receiver_bankcard_number',
  k_receiver_bankcard_name: 'k_receiver_bankcard_name',
  l_receiver_bankcard_code: 'l_receiver_bankcard_code',
  m_financial_system_code: 'm_financial_system_code',
  o_loan_time: 'o_loan_time',
  p_reference: 'p_reference',
  q_outer_sn: 'q_outer_sn',
  r_amount: 'r_amount',
  s_fee: 's_fee',
  t_sync_code: 't_sync_code',
  u_sync_message: 'u_sync_message',
  v_sync_raw: 'v_sync_raw',
  w_callback_code: 'w_callback_code',
  x_callback_message: 'x_callback_message',
  y_callback_raw: 'y_callback_raw',
  z_remark: 'z_remark',
  a_a_certificate: 'a_a_certificate',
  a_b_index: 'a_b_index',
  a_a_a_a_a_d_borrow: FieldIndex2,
};
