// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  id: 'id',
  a_name: '路由名称',
  b_sort: '排序',
  c_borrow: '借款画像',
  d_channel: '渠道画像',
  e_sms: '短信画像',
  f_contact: '通讯录画像',
  g_app: 'app画像',
  h_region: '地区画像',
  i_age: '年龄画像',
  j_risk_strategy_id_1: '策略1',
  k_risk_strategy_1_rate: '策略1占比',
  l_risk_strategy_id_2: '策略2',
  m_risk_strategy_2_rate: '策略2占比',
  n_risk_strategy_id_3: '策略3',
  o_risk_strategy_3_rate: '策略3占比',
  p_description: '路由描述',
  q_status: '状态',
  r_risk_strategy_1_code: '策略1code',
  s_risk_strategy_1_version: '策略1版本',
  t_risk_strategy_2_code: '策略2code',
  u_risk_strategy_2_version: '策略2版本',
  v_risk_strategy_3_code: '策略3code',
  w_risk_strategy_3_version: '策略3版本',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex = {
  id: 'id',
  a_name: 'a_name',
  b_sort: 'b_sort',
  c_borrow: 'c_borrow',
  d_channel: 'd_channel',
  e_sms: 'e_sms',
  f_contact: 'f_contact',
  g_app: 'g_app',
  h_region: 'h_region',
  i_age: 'i_age',
  j_risk_strategy_id_1: 'j_risk_strategy_id_1',
  k_risk_strategy_1_rate: 'k_risk_strategy_1_rate',
  l_risk_strategy_id_2: 'l_risk_strategy_id_2',
  m_risk_strategy_2_rate: 'm_risk_strategy_2_rate',
  n_risk_strategy_id_3: 'n_risk_strategy_id_3',
  o_risk_strategy_3_rate: 'o_risk_strategy_3_rate',
  p_description: 'p_description',
  q_status: 'q_status',
  r_risk_strategy_1_code: 'r_risk_strategy_1_code',
  s_risk_strategy_1_version: 's_risk_strategy_1_version',
  t_risk_strategy_2_code: 't_risk_strategy_2_code',
  u_risk_strategy_2_version: 'u_risk_strategy_2_version',
  v_risk_strategy_3_code: 'v_risk_strategy_3_code',
  w_risk_strategy_3_version: 'w_risk_strategy_3_version',
  created_at: 'created_at',
  updated_at: 'updated_at',
};
