// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  a_name: '名称',
  b_sort: '排序',
  c_borrow: '借款',
  d_channel: '渠道',
  e_sms: '短信',
  f_contact: '通讯录',
  g_app: 'app',
  h_region: '地区',
  i_age: '年龄',
  j_risk_strategy_id_1: '冠军',
  k_risk_risk_strategy_1_rate: '占比',
  l_risk_strategy_id_2: '挑战者A',
  m_risk_strategy_2_rate: '占比',
  n_risk_strategy_id_3: '挑战者B',
  o_risk_strategy_3_rate: '占比',
  p_description: '路由描述',
  q_status: '状态',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex = {
  id: 'id',
  a_name: 'a_name',
  b_sort: 'b_sort',
  c_borrow: 'c_borrow',
  d_channel: 'd_channel',
  e_sms: 'e_sms',
  f_contact: 'f_contact',
  g_app: 'g_app',
  h_region: 'h_region',
  i_age: 'i_age',
  j_risk_strategy_id_1: 'j_risk_strategy_id_1',
  k_risk_strategy_1_rate: 'k_risk_strategy_1_rate',
  l_risk_strategy_id_2: 'l_risk_strategy_id_2',
  m_risk_strategy_2_rate: 'm_risk_strategy_2_rate',
  n_risk_strategy_id_3: 'n_risk_strategy_id_3',
  o_risk_strategy_3_rate: 'o_risk_strategy_3_rate',
  p_description: 'p_description',
  q_status: 'q_status',
  created_at: 'created_at',
  updated_at: 'updated_at',
};
