/**
 * @name umi 的路由配置
 * @description 只支持 path,component,routes,redirect,wrappers,name,icon 的配置
 * @param path  path 只支持两种占位符配置，第一种是动态参数 :id 的形式，第二种是 * 通配符，通配符只能出现路由字符串的最后。
 * @param component 配置 location 和 path 匹配后用于渲染的 React 组件路径。可以是绝对路径，也可以是相对路径，如果是相对路径，会从 src/pages 开始找起。
 * @param routes 配置子路由，通常在需要为多个路径增加 layout 组件时使用。
 * @param redirect 配置路由跳转
 * @param wrappers 配置路由组件的包装组件，通过包装组件可以为当前的路由组件组合进更多的功能。 比如，可以用于路由级别的权限校验
 * @param name 配置路由的标题，默认读取国际化文件 menu.ts 中 menu.xxxx 的值，如配置 name 为 login，则读取 menu.ts 中 menu.login 的取值作为标题
 * @param icon 配置路由的图标，取值参考 https://ant.design/components/icon-cn， 注意去除风格后缀和大小写，如想要配置图标为 <StepBackwardOutlined /> 则取值应为 stepBackward 或 StepBackward，如想要配置图标为 <UserOutlined /> 则取值应为 user 或者 User
 * @doc https://umijs.org/docs/guides/routes
 */
export default [
  {
    path: '/user',
    layout: false,
    routes: [
      {
        name: 'login',
        path: '/user/login',
        component: './User/Login',
      },
    ],
  },
  {
    path: '/welcome',
    name: 'welcome',
    icon: 'DashboardOutlined',
    component: './Welcome',
  },
  {
    path: '/dashboard',
    name: 'dashboard',
    icon: 'dashboard',
    routes: [
      {
        path: '/dashboard',
        redirect: '/dashboard/analysis',
        access: 'normalRouteFilter', 
      },
      {
        name: 'analysis',
        icon: 'smile',
        path: '/dashboard/analysis',
        component: './dashboard/analysis',
        access: 'normalRouteFilter', 
      },
      {
        name: 'analysis2',
        icon: 'smile',
        path: '/dashboard/analysis2',
        component: './dashboard/analysis2',
        access: 'normalRouteFilter', 
      },
      {
        name: 'monitor',
        icon: 'smile',
        path: '/dashboard/monitor',
        component: './dashboard/monitor',
        access: 'normalRouteFilter', 
      },
      {
        name: 'workplace',
        icon: 'smile',
        path: '/dashboard/workplace',
        component: './dashboard/workplace',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    path: '/admin',
    name: 'admin',
    icon: 'crown',
    access: 'canAdmin',
    routes: [
      {
        path: '/admin',
        redirect: '/admin/sub-page',
      },
      {
        path: '/admin/sub-page',
        name: 'sub-page',
        component: './Admin',
      },
    ],
  },
  {
    path: '/',
    redirect: '/welcome',
  },
  {
    name: 'user-manager',
    icon: 'TeamOutlined',
    path: '/user-manager',
    // component: './AUser',
    routes: [
      {
        name: 'user',
        icon: 'smile',
        path: '/user-manager/user',
        component: './UserManager/AUser',
        access: 'normalRouteFilter', 
      },
      {
        name: 'white-info',
        icon: 'smile',
        path: '/user-manager/white-info',
        component: './UserManager/BAWhite',
        access: 'normalRouteFilter', 
      },
      {
        name: 'white',
        icon: 'smile',
        path: '/user-manager/white',
        component: './UserManager/BAWhiteUser',
        hideChildrenInMenu: true,
        routes: [
          {
            name: 'white-user',
            icon: 'smile',
            path: '/user-manager/white/user',
            component: './UserManager/BAWhiteUser/BAWhiteUser',
            access: 'normalRouteFilter', 
          },
          {
            name: 'user-with-overdue',
            icon: 'smile',
            path: '/user-manager/white/user-with-overdue',
            component: './UserManager/BAWhiteUser/BAWhiteUserWithOverdue',
            access: 'normalRouteFilter', 
          },
          {
            name: 'user-with-serious-overdue',
            icon: 'smile',
            path: '/user-manager/white/user-with-serious-overdue',
            component: './UserManager/BAWhiteUser/BAWhiteUserWithSeriousOverdue',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'black-info-list',
        icon: 'smile',
        path: '/user-manager/black-info-list',
        component: './UserManager/RBlack',
        hideChildrenInMenu: true,
        routes: [
          {
            name: 'black-phone-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/phone',
            component: './UserManager/RBlack/Phone', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
          {
            name: 'black-id-number-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/id-number',
            component: './UserManager/RBlack/IdNumber', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
          {
            name: 'black-id-number2-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/id-number2',
            component: './UserManager/RBlack/IdNumber2', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
          {
            name: 'black-bank-card-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/bank-card',
            component: './UserManager/RBlack/BankCard', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
          {
            name: 'black-device-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/device',
            component: './UserManager/RBlack/Device', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
          {
            name: 'black-imei-list',
            icon: 'smile',
            path: '/user-manager/black-info-list/imei',
            component: './UserManager/RBlack/Imei', // hideInMenu:true,
            access: 'normalRouteFilter', 
          },
        ],
      },
      /*{
        name: 'black-user-list',
        icon: 'smile',
        path: '/user-manager/black-user-list',
        component: './UserManager/AIBlackUser',
        hideChildrenInMenu: true,
        routes: [
          {
            name: 'black-user',
            icon: 'smile',
            path: '/user-manager/black-user-list/black-user',
            component: './UserManager/AIBlackUser/BlackUser',
          },
          {
            name: 'black-user-with-repay',
            icon: 'smile',
            path: '/user-manager/black-user-list/black-user-with-repay',
            component: './UserManager/AIBlackUser/BlackUserWithRepay',
          },
        ],
      },*/
      {
        name: 'black-user-list',
        icon: 'smile',
        path: '/user-manager/black-user-list/black-user',
        component: './UserManager/AIBlackUser/BlackUser',
        access: 'normalRouteFilter', 
      },
      {
        name: 'g-b-marketing',
        icon: 'smile',
        path: '/user-manager/g-b-marketing',
        component: './UserManager/GBMarketing',
        access: 'normalRouteFilter', 
      },
      {
        name: 'marketing-detail-list',
        icon: 'smile',
        path: '/user-manager/marketing-detail-list',
        component: './UserManager/GCMarketingDetail',
        hideChildrenInMenu: true,
        routes: [
          {
            name: 'marketing-success-user',
            icon: 'smile',
            path: '/user-manager/marketing-detail-list/marketing-success-user',
            component: './UserManager/GCMarketingDetail/MarketingSuccessUser',
            access: 'normalRouteFilter', 
          },
          {
            name: 'marketing-user-with-overdue',
            icon: 'smile',
            path: '/user-manager/marketing-detail-list/marketing-user-with-overdue',
            component: './UserManager/GCMarketingDetail/MarketingUserWithOverdue',
            access: 'normalRouteFilter', 
          },
          {
            name: 'marketing-list',
            icon: 'smile',
            path: '/user-manager/marketing-detail-list/marketing-list',
            component: './UserManager/GCMarketingDetail/MarketingList',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'import-result-list',
        icon: 'smile',
        path: '/user-manager/import-result-list',
        component: './UserManager/BEImportResult',
        access: 'normalRouteFilter', 
      },
    ],
  },

  {
    name: 'borrow',
    icon: 'ContainerOutlined',
    path: '/borrow',
    routes: [
      {
        name: 'borrow-list',
        icon: 'smile',
        path: '/borrow/borrow-list',
        component: './Borrow/BorrowList',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loaned-list',
        icon: 'smile',
        path: '/borrow/loan-list',
        component: './Borrow/LoanList',
        access: 'normalRouteFilter', 
      },
      /*{
        name: 'recently-list',
        icon: 'smile',
        path: '/borrow/outstanding-list',
        component: './Borrow/OutstandingList',
      },
      {
        name: 'overdue-list',
        icon: 'smile',
        path: '/borrow/outstanding-list',
        component: './Borrow/OutstandingList',
      },*/
      /*      {
              name: 'outstanding-list',
              icon: 'smile',
              path: '/borrow/outstanding-list',
              component: './Borrow/OutstandingList',
            },*/
      {
        name: 'verify-list',
        icon: 'smile',
        path: '/borrow/verify-list',
        component: './Borrow/VerifyList',
        access: 'normalRouteFilter', 
      },
      {
        name: 'verify-detail',
        icon: 'smile',
        path: '/borrow/verify/detail/:id',
        component: './Borrow/VerifyList/Detail',
        hideInMenu: true,
        access: 'normalRouteFilter', 
      },
      {
        name: 'borrow-detail',
        icon: 'smile',
        path: '/borrow/detail/:id',
        component: './Borrow/BorrowList/Detail',
        hideInMenu: true,
        hideChildrenInMenu: true,
        access: 'normalRouteFilter', 
        routes: [
          {
            name: 'urge-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/urge/:urgeId',
            component: './Borrow/BorrowList/components/UrgeDetail',
            access: 'normalRouteFilter', 
          },
          {
            name: 'verify-detail2',
            icon: 'smile',
            path: '/borrow/detail/:id/verify/:verifyId',
            component: './Borrow/VerifyList/components/VerifyDetail',
            access: 'normalRouteFilter', 
          },
          {
            name: 'sms-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/sms/:userId',
            component: './Borrow/BorrowList/components/SmsDetail',
            access: 'normalRouteFilter', 
          },
          {
            name: 'sms-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/risk/:riskId',
            component: './Risk/RiskResult/components/DetailList',
            access: 'normalRouteFilter', 
          },
          {
            name: 'app-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/app/:userId',
            component: './Borrow/BorrowList/components/AppDetail',
            access: 'normalRouteFilter', 
          },
          {
            name: 'contact-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/contact/:userId',
            component: './Borrow/BorrowList/components/ContactDetail',
            access: 'normalRouteFilter', 
          },
          {
            name: 'contact-detail',
            icon: 'smile',
            path: '/borrow/detail/:id/device/:userId',
            component: './Borrow/BorrowList/components/DeviceDetail',
            access: 'normalRouteFilter', 
          },
        ],
      },
    ],
  },
  {
    name: 'review',
    icon: 'FileSearchOutlined',
    path: '/review',
    routes: [
      {
        name: 'review-group',
        icon: 'smile',
        path: '/review/review-group',
        component: './Review/ReviewGroup',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-admin',
        icon: 'smile',
        path: '/review/review-admin',
        component: './Review/ReviewAdmin',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-borrow',
        icon: 'smile',
        path: '/review/review-borrow',
        component: './Review/ReviewBorrow',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-borrow-accept',
        icon: 'smile',
        path: '/review/review-borrow-accept',
        component: './Review/ReviewBorrowAccept',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-borrow-reject',
        icon: 'smile',
        path: '/review/review-borrow-reject',
        component: './Review/ReviewBorrowReject',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-borrow-flow',
        icon: 'smile',
        path: '/review/review-borrow-flow',
        component: './Review/ReviewBorrowFlow',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    name: 'loan',
    icon: 'BankOutlined',
    path: '/loan',
    routes: [
      {
        name: 'waiting-loan',
        icon: 'smile',
        path: '/loan/waiting-loan',
        component: './Loan/WaitingLoan',
        access: 'normalRouteFilter', 
      },
      {
        name: 'queue-loan',
        icon: 'smile',
        path: '/loan/queue-loan',
        component: './Loan/QueueLoan',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loan-list',
        icon: 'smile',
        path: '/loan/loan-list',
        component: './Loan/LoanList',
        hideChildrenInMenu: true,
        routes: [
          {
            name: 'success-loan',
            icon: 'smile',
            path: '/loan/loan-list/success-loan',
            component: './Loan/LoanList/SuccessLoan',
            access: 'normalRouteFilter', 
          },
          {
            name: 'fail-loan',
            icon: 'smile',
            path: '/loan/loan-list/fail-loan',
            component: './Loan/LoanList/FailLoan',
            access: 'normalRouteFilter', 
          },
          {
            name: 'intercept-loan',
            icon: 'smile',
            path: '/loan/loan-list/intercept',
            component: './Loan/LoanList/InterceptLoan',
            access: 'normalRouteFilter', 
          },
          {
            name: 'processing-loan',
            icon: 'smile',
            path: '/loan/loan-list/processing',
            component: './Loan/LoanList/ProcessingLoan',
            access: 'normalRouteFilter', 
          },
          {
            name: 'unknown-loan',
            icon: 'smile',
            path: '/loan/loan-list/unknown',
            component: './Loan/LoanList/UnknownLoan',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'loan-log',
        icon: 'smile',
        path: '/loan/log',
        component: './Loan/LoanLog',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    name: 'repay',
    icon: 'CreditCardOutlined',
    path: '/repay',
    routes: [
      {
        name: 'repay-list',
        icon: 'smile',
        path: '/repay/list',
        component: './Repay/RepayList',
        access: 'normalRouteFilter', 
      },
      {
        name: 'repay-log',
        icon: 'smile',
        path: '/repay/log',
        component: './Repay/RepayLog',
        access: 'normalRouteFilter', 
      },
      {
        name: 'extend-list',
        icon: 'smile',
        path: '/repay/extend-list',
        component: './Repay/ExtendList',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    name: 'telemarketing',
    icon: 'PhoneOutlined',
    path: '/telemarketing',
    routes: [
      {
        name: 'telemarketing-role',
        icon: 'smile',
        path: '/telemarketing/role',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'telemarketing-admin-list',
        icon: 'smile',
        path: '/telemarketing/admin-list',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'my-telemarketing',
        icon: 'smile',
        path: '/telemarketing/my-telemarketing',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'telemarketing-order-flow-history',
        icon: 'smile',
        path: '/telemarketing/order-flow-history',
        component: './Stay',
        access: 'normalRouteFilter', 
      },

    ],
  },
  {
    name: 'collection',
    icon: 'CommentOutlined',
    path: '/collection',
    routes: [
      {
        name: 'collection-agency-list',
        icon: 'smile',
        path: '/collection/collection-agency-list',
        component: './Collection/CollectionAgency',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-group-list',
        icon: 'smile',
        path: '/collection/collection-group-list',
        component: './Collection/CollectionGroup',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-admin-list',
        icon: 'smile',
        path: '/collection/collection-admin-list',
        component: './Collection/CollectionAdmin',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-role',
        icon: 'smile',
        path: '/collection/collection-role',
        component: './Collection/CollectionRole',
        access: 'normalRouteFilter', 
      },
      {
        name: 'my-collection',
        icon: 'smile',
        path: '/collection/my-collection',
        component: './Collection/MyCollection',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-order-flow-history',
        icon: 'smile',
        path: '/collection/collection-order-flow-history',
        component: './Collection/CollectionOrderFlowHistory',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-assign-log',
        icon: 'smile',
        path: '/collection/collection-assign-log',
        component: './Collection/CollectionAssignLog',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-news',
        icon: 'smile',
        path: '/collection/collection-news',
        component: './Collection/CollectionNews',
        access: 'normalRouteFilter', 
      },
    ],
  },

  {
    name: 'risk',
    icon: 'AlertOutlined',
    path: '/risk',
    routes: [
      {
        name: 'risk-item-cat',
        icon: 'smile',
        path: '/risk/risk-item-cat',
        component: './Risk/RiskItemCat',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-item',
        icon: 'smile',
        path: '/risk/risk-item',
        component: './Risk/RiskItem',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-role-bundle',
        icon: 'smile',
        path: '/risk/risk-role-bundle',
        component: './Risk/RiskRoleBundle',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-role-bundle-detail',
        icon: 'smile',
        path: '/risk/risk-role-bundle/detail/:id',
        component: './Risk/RiskRoleBundle/Detail',
        hideInMenu: true,
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-tag2',
        icon: 'smile',
        path: '/risk/risk-tag',
        component: './Risk/RiskTag',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-strategy-bundle',
        icon: 'smile',
        path: '/risk/risk-strategy-bundle',
        component: './Risk/RiskStrategyBundle',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-strategy-bundle-detail',
        icon: 'smile',
        path: '/risk/risk-strategy-bundle/detail/:id',
        component: './Risk/RiskStrategyBundle/Detail',
        hideInMenu: true,
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-strategy-route',
        icon: 'smile',
        path: '/risk/risk-strategy-route',
        component: './Risk/RiskStrategyRoute',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-result',
        icon: 'smile',
        path: '/risk/risk-result',
        component: './Risk/RiskResult',
        access: 'normalRouteFilter', 
      },
      {
        name: 'risk-back-tracking',
        icon: 'smile',
        path: '/risk/risk-back-tracking',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    name: 'operation',
    icon: 'ProductOutlined',
    path: '/operation',
    routes: [
      {
        name: 'product',
        icon: 'smile',
        path: '/operation/product',
        component: './Operation/BProduct',
        access: 'normalRouteFilter',
        
      },
      {
        name: 'product-detail',
        icon: 'smile',
        path: '/operation/product/detail/:id',
        component: './Operation/BProduct/Detail',
        hideInMenu: true,
        access: 'normalRouteFilter', 
      },
      {
        name: 'channel',
        icon: 'smile',
        path: '/operation/channel',
        component: './Operation/Channel',
        access: 'normalRouteFilter',
      },
      {
        name: 'payment-channel',
        icon: 'smile',
        path: '/operation/payment-channel',
        component: './Operation/PaymentChannel',
        access: 'normalRouteFilter',
      },
      {
        name: 'kyc',
        icon: 'smile',
        path: '/operation/kyc',
        component: './Operation/Kyc',
        access: 'normalRouteFilter',
      },
      {
        name: 'credit',
        icon: 'smile',
        path: '/operation/credit',
        component: './Operation/Credit',
        access: 'normalRouteFilter',
      },
      {
        name: 'sms',
        icon: 'smile',
        path: '/operation/sms',
        routes: [
          {
            name: 'template',
            icon: 'smile',
            path: '/operation/sms/template',
            component: './Operation/Sms/Template',
            access: 'normalRouteFilter',
          },
          {
            name: 'custom',
            icon: 'smile',
            path: '/operation/sms/custom',
            component: './Operation/Sms/Custom',
            access: 'normalRouteFilter',
          },
        ],
      },
      {
        name: 'app',
        icon: 'smile',
        path: '/operation/app',
        routes: [
          {
            name: 'push',
            icon: 'smile',
            path: '/operation/app/push',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'news',
            icon: 'smile',
            path: '/operation/app/news',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'banner',
            icon: 'smile',
            path: '/operation/app/banner',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'service',
            icon: 'smile',
            path: '/operation/app/service',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'node',
            icon: 'smile',
            path: '/operation/app/node',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'point',
            icon: 'smile',
            path: '/operation/app/point',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'update',
            icon: 'smile',
            path: '/operation/app/update',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'agreement',
            icon: 'smile',
            path: '/operation/app/agreement',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'market',
        icon: 'smile',
        path: '/operation/market',
        routes: [
          {
            name: 'competitors-list',
            icon: 'smile',
            path: '/operation/market/competitors-list',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'competitors',
            icon: 'smile',
            path: '/operation/market/competitors',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
          {
            name: 'trend',
            icon: 'smile',
            path: '/operation/market/trend',
            component: './Stay',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'feedback',
        icon: 'smile',
        path: '/operation/feedback',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loss',
        icon: 'smile',
        path: '/operation/loss',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
    ],
  },
  {
    name: 'statistics',
    icon: 'FundOutlined',
    path: '/statistics',
    routes: [
      {
        name: 'register',
        icon: 'smile',
        path: '/statistics/register',
        routes: [
          {
            name: 'marketing',
            icon: 'smile',
            path: '/statistics/register/marketing',
            component: './Statistics/Register/Marketing',
            access: 'normalRouteFilter', 
          },
          {
            name: 'daily-report',
            icon: 'smile',
            path: '/statistics/register/daily-report',
            component: './Statistics/Register/DailyReport',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'overdue',
        icon: 'smile',
        path: '/statistics/overdue',
        routes: [
          {
            name: 'product2',
            icon: 'smile',
            path: '/statistics/overdue/product',
            component: './Statistics/Overdue/Product',
            access: 'normalRouteFilter', 
          },
          {
            name: 'multi-dimension',
            icon: 'smile',
            path: '/statistics/overdue/multi-dimension',
            component: './Statistics/Overdue/MultiDimension',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'loan-overdue',
        icon: 'smile',
        path: '/statistics/loan-overdue',
        routes: [
          {
            name: 'product3',
            icon: 'smile',
            path: '/statistics/loan-overdue/product',
            component: './Statistics/LoanOverdue/Product',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'profit',
        icon: 'smile',
        path: '/statistics/profit',
        routes: [
          {
            name: 'product4',
            icon: 'smile',
            path: '/statistics/profit/product',
            component: './Statistics/Profit/Product',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'risk',
        icon: 'smile',
        path: '/statistics/risk',
        routes: [
          {
            name: 'overdue-risk-item-range',
            icon: 'smile',
            path: '/statistics/risk/overdue-risk-item-range',
            component: './Statistics/Risk/OverdueRiskItemRange',
            access: 'normalRouteFilter', 
          },
          {
            name: 'risk-bundle',
            icon: 'smile',
            path: '/statistics/risk/risk-bundle',
            component: './Statistics/Risk/RiskBundle',
            access: 'normalRouteFilter', 
          },
          {
            name: 'risk-strategy',
            icon: 'smile',
            path: '/statistics/risk/risk-strategy',
            component: './Statistics/Risk/RiskStrategy',
            access: 'normalRouteFilter', 
          },
          {
            name: 'risk-tag',
            icon: 'smile',
            path: '/statistics/risk/risk-tag',
            component: './Statistics/Risk/RiskTag',
            access: 'normalRouteFilter', 
          },
          {
            name: 'risk-region',
            icon: 'smile',
            path: '/statistics/risk/risk-region',
            component: './Statistics/Risk/RiskRegion',
            access: 'normalRouteFilter', 
          },
          {
            name: 'risk-tree',
            icon: 'smile',
            path: '/statistics/risk/risk-tree',
            component: './Statistics/Risk/RiskTree',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'collection',
        icon: 'smile',
        path: '/statistics/collection',
        routes: [
          {
            name: 'admin-news',
            icon: 'smile',
            path: '/statistics/collection/admin-news',
            component: './Statistics/Collection/AdminNews',
            access: 'normalRouteFilter', 
          },
          {
            name: 'admin2',
            icon: 'smile',
            path: '/statistics/collection/admin',
            component: './Statistics/Collection/Admin',
            access: 'normalRouteFilter', 
          },
          {
            name: 'admin-heatmap',
            icon: 'smile',
            path: '/statistics/collection/admin-heatmap',
            component: './Statistics/Collection/AdminHeatmap',
            access: 'normalRouteFilter', 
          },
          {
            name: 'report',
            icon: 'smile',
            path: '/statistics/collection/report',
            component: './Statistics/Collection/Report',
            access: 'normalRouteFilter', 
          },
          {
            name: 'flow',
            icon: 'smile',
            path: '/statistics/collection/flow',
            component: './Statistics/Collection/Flow',
            access: 'normalRouteFilter', 
          },

        ],
      },

      {
        name: 'sms',
        icon: 'smile',
        path: '/statistics/sms',
        routes: [
          {
            name: 'back-fill',
            icon: 'smile',
            path: '/statistics/sms/back-fill',
            component: './Statistics/Sms/BackFill',
            access: 'normalRouteFilter', 
          },
          {
            name: 'report2',
            icon: 'smile',
            path: '/statistics/sms/report',
            component: './Statistics/Sms/Report',
            access: 'normalRouteFilter', 
          },
          {
            name: 'template2',
            icon: 'smile',
            path: '/statistics/sms/template',
            component: './Statistics/Sms/Template',
            access: 'normalRouteFilter', 
          },
        ],
      },
      {
        name: 'finance',
        icon: 'smile',
        path: '/statistics/finance',
        routes: [
          {
            name: 'fee',
            icon: 'smile',
            path: '/statistics/finance/fee',
            component: './Statistics/Finance/Fee',
            access: 'normalRouteFilter', 
          },
        ],
      },
    ],
  },
  {
    name: 'finance',
    icon: 'CalculatorOutlined',
    path: '/finance',
    routes: [
      {
        name: 'collection-agency-day',
        icon: 'smile',
        path: '/finance/collection-agency-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-agency-month',
        icon: 'smile',
        path: '/finance/collection-agency-month',
        component: './Stay',
        access: 'normalRouteFilter', 
      },

      {
        name: 'collection-admin-day',
        icon: 'smile',
        path: '/finance/collection-admin-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'collection-admin-month',
        icon: 'smile',
        path: '/finance/collection-admin-month',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-admin-day',
        icon: 'smile',
        path: '/finance/review-admin-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'review-admin-month',
        icon: 'smile',
        path: '/finance/review-admin-month',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'telemarketing-admin-day',
        icon: 'smile',
        path: '/finance/telemarketing-admin-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'telemarketing-admin-month',
        icon: 'smile',
        path: '/finance/telemarketing-admin-month',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loan-day',
        icon: 'smile',
        path: '/finance/loan-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },

      {
        name: 'repay-day',
        icon: 'smile',
        path: '/finance/repay-day',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loan-repay-week',
        icon: 'smile',
        path: '/finance/loan-repay-week',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'loan-repay-month',
        icon: 'smile',
        path: '/finance/loan-repay-month',
        component: './Stay',
        access: 'normalRouteFilter', 
      },
      {
        name: 'supplier',
        icon: 'smile',
        path: '/finance/supplier',
        component: './Stay',
        access: 'normalRouteFilter', 
      },

    ],
  },
  {
    name: 'setting',
    icon: 'SettingOutlined',
    path: '/setting',
    routes: [
      {
        name: 'system-setting',
        icon: 'smile',
        path: '/setting/system-setting',
        component: './Setting/SystemSettings',
        access: 'normalRouteFilter', 
      },
      {
        name: 'verify-item',
        icon: 'smile',
        path: '/setting/verify-item',
        component: './Setting/QVerifyItem',
        access: 'normalRouteFilter', 
      },
      {
        name: 'role',
        icon: 'smile',
        path: '/setting/role',
        component: './Setting/Role',
        access: 'normalRouteFilter', 
      },
    ],
  },

  {
    component: './404',
  },
];
