// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  a_borrow_id: '订单id',
  b_admin_id: '管理员id',
  c_result: '审核结果',
  d_id_number_result: '证件号',
  e_contact_persion_result: '联系人',
  f_job_result: '工作信息',
  g_contact_result: '通讯录',
  h_sms_result: '短信',
  i_risk_result: '风控',
  j_app_result: 'app',
  k_history_result: '历史订单',
  l_flow_count: '流转次数',
  m_review_group_id: '审核组',
  n_borrow_times_type: '借款类型种类',
  o_device_result: '设备',
  p_bank_result: '银行',
  q_comment: '备注',
  r_liveness_result: '活体',
  s_ocr_result: 'ocr',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex = {
  a_borrow_id: 'a_borrow_id',
  b_admin_id: 'b_admin_id',
  c_result: 'c_result',
  d_id_number_result: 'd_id_number_result',
  e_contact_persion_result: 'e_contact_persion_result',
  f_job_result: 'f_job_result',
  g_contact_result: 'g_contact_result',
  h_sms_result: 'h_sms_result',
  i_risk_result: 'i_risk_result',
  j_app_result: 'j_app_result',
  k_history_result: 'k_history_result',
  l_flow_count: 'l_flow_count',
  m_review_group_id: 'm_review_group_id',
  n_borrow_times_type: 'n_borrow_times_type',
  o_device_result: 'o_device_result',
  p_bank_result: 'p_bank_result',
  q_comment: 'q_comment',
  r_liveness_result: 'r_liveness_result',
  s_ocr_result: 's_ocr_result',
  created_at: 'created_at',
  updated_at: 'updated_at',
};

export const FieldLabels2 = {
  a_borrow_id: '订单id',
  b_before_admin_id: '流转之前审核组',
  c_before_admin_id: '流转之前管理员',
  d_after_admin_id: '流转之后管理员',
  e_after_admin_id: '流转之后管理员',
  f_admin_id: '操作管理员',
  created_at: '创建时间',
};
export const FieldIndex2 = {
  a_borrow_id: 'a_borrow_id',
  b_before_admin_id: 'b_before_admin_id',
  c_before_admin_id: 'c_before_admin_id',
  d_after_admin_id: 'd_after_admin_id',
  e_after_admin_id: 'e_after_admin_id',
  f_admin_id: 'f_admin_id',
  created_at: 'created_at',
};
