// @ts-ignore
/* eslint-disable */

export const fieldLabels = {
  b_name: '产品名称',
  c_amount: '产品额度',
  d_unit: '产品单位',
  e_life: '产品周期',
  f_settlement_type: '结算方式',
  g_interest: '利息',
  h_service_fee_rate: '服务费率',
  i_overdue_rate: '罚息',
  j_violate_fee_rate: '违约金费率',
  k_extend_rate: '展期费率',
  l_min_pay: '最低还款金额',
  m_can_part_pay: '是否允许部分还款',
  n_can_extend: '是否可以展期',
  o_type: '产品类型',
  p_url: '产品链接',
  q_unlock_credit_fraction: '解锁信用分',
  r_settled_times: '最小结清次数',
  s_max_overdue_days: '最大逾期天数',
  t_max_overdue_times: '最大逾期次数',
  u_status: '状态',
  v_sort: '展示排序',
  x_introduction: '描述',
  y_comment: '备注',
  z_period: '产品期数',
  a_a_amount_type: '产品额度类型',
  a_b_day_valid_count: '每日可借数量',
  a_d_tags: '产品标签',
  a_e_features: '产品特点',
};
