// @ts-ignore
/* eslint-disable */

export const FieldLabels = {
  id: 'id',
  a_user_id: '用户id',
  b_borrow_id: '订单id',
  c_verify_id: '认证id',
  d_risk_strategy_route_id: '决策路由',
  e_risk_strategy_id: '决策',
  f_admin_id: '人审管理员',
  g_phone: '手机号码',
  h_borrow_sn: '订单号',
  i_amount: '订单金额',
  j_borrow_count: '借款次数',
  k_machine_result: '机审结果',
  l_review_result: '人审结果',
  m_score: '信用分',
  n_reject_risk_role_count: '拒绝数',
  o_accept_risk_role_count: '通过数',
  p_review_risk_role_count: '人审数',
  q_refuse_risk_role_rate: '拒绝占比',
  r_channel: '渠道',
  s_sms: '短信',
  t_contact: '通讯录',
  u_app: 'app',
  v_region: '地区',
  w_age: '年龄',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex = {
  id: 'id',
  a_user_id: 'a_user_id',
  b_borrow_id: 'b_borrow_id',
  c_verify_id: 'c_verify_id',
  d_risk_strategy_route_id: 'd_risk_strategy_route_id',
  e_risk_strategy_id: 'e_risk_strategy_id',
  f_admin_id: 'f_admin_id',
  g_phone: 'g_phone',
  h_borrow_sn: 'h_borrow_sn',
  i_amount: 'i_amount',
  j_borrow_count: 'j_borrow_count',
  k_machine_result: 'k_machine_result',
  l_review_result: 'l_review_result',
  m_score: 'm_score',
  n_reject_risk_role_count: 'n_reject_risk_role_count',
  o_accept_risk_role_count: 'o_accept_risk_role_count',
  p_review_risk_role_count: 'p_review_risk_role_count',
  q_refuse_risk_role_rate: 'q_refuse_risk_role_rate',
  r_channel: 'r_channel',
  s_sms: 's_sms',
  t_contact: 't_contact',
  u_app: 'u_app',
  v_region: 'v_region',
  w_age: 'w_age',
  created_at: 'created_at',
  updated_at: 'updated_at',
};
export const FieldLabels2 = {
  id: 'id',
  a_user_id: '用户id',
  b_borrow_id: '订单id',
  c_verify_id: '认证id',
  d_risk_strategy_route_id: '决策路由',
  e_risk_strategy_id: '决策',
  f_risk_role_bundle_id: '规则id',
  g_risk_role_group_id: '细则组id',
  h_risk_role_id: '细则id',
  i_risk_role_group_result: '组机审结果',
  j_risk_role_result: '细则机审结果',
  k_value: '输入值',
  l_score: '分值',
  m_right_value: '右侧值',
  n_risk_item_id: '字段',
  o_right_risk_item_id: '右侧字段',
  p_borrow_risk_result_id: '风控结果',
  created_at: '创建时间',
  updated_at: '更新时间',
};
export const FieldIndex2 = {
  id: 'id',
  a_user_id: 'a_user_id',
  b_borrow_id: 'b_borrow_id',
  c_verify_id: 'c_verify_id',
  d_risk_strategy_route_id: 'd_risk_strategy_route_id',
  e_risk_strategy_id: 'e_risk_strategy_id',
  f_risk_role_bundle_id: 'f_risk_role_bundle_id',
  g_risk_role_group_id: 'g_risk_role_group_id',
  h_risk_role_id: 'h_risk_role_id',
  i_risk_role_group_result: 'i_risk_role_group_result',
  j_risk_role_result: 'j_risk_role_result',
  k_value: 'k_value',
  l_score: 'l_score',
  m_right_value: 'm_right_value',
  n_risk_item_id: 'n_risk_item_id',
  o_right_risk_item_id: 'o_right_risk_item_id',
  p_borrow_risk_result_id: 'p_borrow_risk_result_id',
  created_at: 'created_at',
  updated_at: 'updated_at',
};
