// @ts-ignore
/* eslint-disable */
export const FieldRateLabels = {
  collection_success_amount_rate: '金额催回率',
  collection_success_count_rate: '数量催回率',
  'dpd-3_collection_success_amount_rate': 'DPD-3金额催回率',
  'dpd-3_collection_success_count_rate': 'DPD-3数量催回率',
  'dpd-2_collection_success_amount_rate': 'DPD-2金额催回率',
  'dpd-2_collection_success_count_rate': 'DPD-2数量催回率',
  'dpd-1_collection_success_amount_rate': 'DPD-1金额催回率',
  'dpd-1_collection_success_count_rate': 'DPD-1数量催回率',
  dpd0_collection_success_amount_rate: 'DPD-0金额催回率',
  dpd0_collection_success_count_rate: 'DPD-0数量催回数',
  dpd1_collection_success_amount_rate: 'DPD-1金额催回率',
  dpd1_collection_success_count_rate: 'DPD-1数量催回数',
  dpd2_collection_success_amount_rate: 'DPD-2金额催回率',
  dpd2_collection_success_count_rate: 'DPD-2数量催回数',
  dpd3_collection_success_amount_rate: 'DPD-3金额催回率',
  dpd3_collection_success_count_rate: 'DPD-3数量催回数',
  dpd4_collection_success_amount_rate: 'DPD-4金额催回率',
  dpd4_collection_success_count_rate: 'DPD-4数量催回数',
  dpd5_collection_success_amount_rate: 'DPD-5金额催回率',
  dpd5_collection_success_count_rate: 'DPD-5数量催回数',
  dpd6_collection_success_amount_rate: 'DPD-6金额催回率',
  dpd6_collection_success_count_rate: 'DPD-6数量催回数',
  dpd7_collection_success_amount_rate: 'DPD-7金额催回率',
  dpd7_collection_success_count_rate: 'DPD-7数量催回数',
  'dpd8-15_collection_success_amount_rate': 'DPD8-15金额催回率',
  'dpd8-15_collection_success_count_rate': 'DPD8-15数量催回率',
  'dpd16-30_collection_success_amount_rate': 'DPD16-30金额催回率',
  'dpd16-30_collection_success_count_rate': 'DPD16-30数量催回率',
  'dpd31_collection_success_amount_rate': 'DPD31金额催回率',
  'dpd31_collection_success_count_rate': 'DPD31数量催回率',
}
export const FieldRateIndex = {
  collection_success_amount_rate: '金额催回率',
  collection_success_count_rate: '数量催回率',
  'dpd-3_collection_success_amount_rate': 'DPD-3金额催回率',
  'dpd-3_collection_success_count_rate': 'DPD-3数量催回率',
  'dpd-2_collection_success_amount_rate': 'DPD-2金额催回率',
  'dpd-2_collection_success_count_rate': 'DPD-2数量催回率',
  'dpd-1_collection_success_amount_rate': 'DPD-1金额催回率',
  'dpd-1_collection_success_count_rate': 'DPD-1数量催回率',
  dpd0_collection_success_amount_rate: 'DPD-0金额催回率',
  dpd0_collection_success_count_rate: 'DPD-0数量催回数',
  dpd1_collection_success_amount_rate: 'DPD-1金额催回率',
  dpd1_collection_success_count_rate: 'DPD-1数量催回数',
  dpd2_collection_success_amount_rate: 'DPD-2金额催回率',
  dpd2_collection_success_count_rate: 'DPD-2数量催回数',
  dpd3_collection_success_amount_rate: 'DPD-3金额催回率',
  dpd3_collection_success_count_rate: 'DPD-3数量催回数',
  dpd4_collection_success_amount_rate: 'DPD-4金额催回率',
  dpd4_collection_success_count_rate: 'DPD-4数量催回数',
  dpd5_collection_success_amount_rate: 'DPD-5金额催回率',
  dpd5_collection_success_count_rate: 'DPD-5数量催回数',
  dpd6_collection_success_amount_rate: 'DPD-6金额催回率',
  dpd6_collection_success_count_rate: 'DPD-6数量催回数',
  dpd7_collection_success_amount_rate: 'DPD-7金额催回率',
  dpd7_collection_success_count_rate: 'DPD-7数量催回数',
  'dpd8-15_collection_success_amount_rate': 'DPD8-15金额催回率',
  'dpd8-15_collection_success_count_rate': 'DPD8-15数量催回率',
  'dpd16-30_collection_success_amount_rate': 'DPD16-30金额催回率',
  'dpd16-30_collection_success_count_rate': 'DPD16-30数量催回率',
  'dpd31_collection_success_amount_rate': 'DPD31金额催回率',
  'dpd31_collection_success_count_rate': 'DPD31数量催回率',
}
export const FieldLabels = {
  id: 'id',
  a_date: '首次入催日期',
  b_period_index: '期数',
  d_count: '入催数',
  e_amount: '入催额',
  settled_count: '结清数',
  settled_amount: '结清金额',
  part_count: '部分还款数',
  part_amount: '部分还款金额',
  extend_count: '展期数',
  extend_amount: '展期金额',
  collection_success_amount: '催回额',
  collection_success_count: '催回数',
  collection_fail_amount: '待催回额',
  collection_fail_count: '待催回数',
  'dpd-3_settled_count': 'DPD-3结清数',
  'dpd-3_settled_amount': 'DPD-3结清金额',
  'dpd-3_part_count': 'DPD-3部分还款数',
  'dpd-3_part_amount': 'DPD-3部分还款金额',
  'dpd-3_extend_count': 'DPD-3展期数',
  'dpd-3_extend_amount': 'DPD-3展期金额',
  'dpd-3_collection_success_amount': 'DPD-3催回额',
  'dpd-3_collection_success_count': 'DPD-3催回数',
  'dpd-2_settled_count': 'DPD-2结清数',
  'dpd-2_settled_amount': 'DPD-2结清金额',
  'dpd-2_part_count': 'DPD-2部分还款数',
  'dpd-2_part_amount': 'DPD-2部分还款金额',
  'dpd-2_extend_count': 'DPD-2展期数',
  'dpd-2_extend_amount': 'DPD-2展期金额',
  'dpd-2_collection_success_amount': 'DPD-2催回额',
  'dpd-2_collection_success_count': 'DPD-2催回数',
  'dpd-1_settled_count': 'DPD-1结清数',
  'dpd-1_settled_amount': 'DPD-1结清金额',
  'dpd-1_part_count': 'DPD-1部分还款数',
  'dpd-1_part_amount': 'DPD-1部分还款金额',
  'dpd-1_extend_count': 'DPD-1展期数',
  'dpd-1_extend_amount': 'DPD-1展期金额',
  'dpd-1_collection_success_amount': 'DPD-1催回额',
  'dpd-1_collection_success_count': 'DPD-1催回数',
  dpd0_settled_count: 'DPD-0结清数',
  dpd0_settled_amount: 'DPD-0结清金额',
  dpd0_part_count: 'DPD-0部分还款数',
  dpd0_part_amount: 'DPD-0部分还款金额',
  dpd0_extend_count: 'DPD-0展期数',
  dpd0_extend_amount: 'DPD-0展期金额',
  dpd0_collection_success_amount: 'DPD-0催回额',
  dpd0_collection_success_count: 'DPD-0催回数',
  dpd1_settled_count: 'DPD1结清数',
  dpd1_settled_amount: 'DPD1结清金额',
  dpd1_part_count: 'DPD1部分还款数',
  dpd1_part_amount: 'DPD1部分还款金额',
  dpd1_extend_count: 'DPD1展期数',
  dpd1_extend_amount: 'DPD1展期金额',
  dpd1_collection_success_amount: 'DPD1催回额',
  dpd1_collection_success_count: 'DPD1催回数',
  dpd2_settled_count: 'DPD2结清数',
  dpd2_settled_amount: 'DPD2结清金额',
  dpd2_part_count: 'DPD2部分还款数',
  dpd2_part_amount: 'DPD2部分还款金额',
  dpd2_extend_count: 'DPD2展期数',
  dpd2_extend_amount: 'DPD2展期金额',
  dpd2_collection_success_amount: 'DPD2催回额',
  dpd2_collection_success_count: 'DPD2催回数',
  dpd3_settled_count: 'DPD3结清数',
  dpd3_settled_amount: 'DPD3结清金额',
  dpd3_part_count: 'DPD3部分还款数',
  dpd3_part_amount: 'DPD3部分还款金额',
  dpd3_extend_count: 'DPD3展期数',
  dpd3_extend_amount: 'DPD3展期金额',
  dpd3_collection_success_amount: 'DPD3催回额',
  dpd3_collection_success_count: 'DPD3催回数',
  dpd4_settled_count: 'DPD4结清数',
  dpd4_settled_amount: 'DPD4结清金额',
  dpd4_part_count: 'DPD4部分还款数',
  dpd4_part_amount: 'DPD4部分还款金额',
  dpd4_extend_count: 'DPD4展期数',
  dpd4_extend_amount: 'DPD4展期金额',
  dpd4_collection_success_amount: 'DPD4催回额',
  dpd4_collection_success_count: 'DPD4催回数',
  dpd5_settled_count: 'DPD5结清数',
  dpd5_settled_amount: 'DPD5结清金额',
  dpd5_part_count: 'DPD5部分还款数',
  dpd5_part_amount: 'DPD5部分还款金额',
  dpd5_extend_count: 'DPD5展期数',
  dpd5_extend_amount: 'DPD5展期金额',
  dpd5_collection_success_amount: 'DPD5催回额',
  dpd5_collection_success_count: 'DPD5催回数',
  dpd6_settled_count: 'DPD6结清数',
  dpd6_settled_amount: 'DPD6结清金额',
  dpd6_part_count: 'DPD6部分还款数',
  dpd6_part_amount: 'DPD6部分还款金额',
  dpd6_extend_count: 'DPD6展期数',
  dpd6_extend_amount: 'DPD6展期金额',
  dpd6_collection_success_amount: 'DPD6催回额',
  dpd6_collection_success_count: 'DPD6催回数',
  dpd7_settled_count: 'DPD7结清数',
  dpd7_settled_amount: 'DPD7结清金额',
  dpd7_part_count: 'DPD7部分还款数',
  dpd7_part_amount: 'DPD7部分还款金额',
  dpd7_extend_count: 'DPD7展期数',
  dpd7_extend_amount: 'DPD7展期金额',
  dpd7_collection_success_amount: 'DPD7催回额',
  dpd7_collection_success_count: 'DPD7催回数',
  'dpd8-15_settled_count': 'DPD8-15结清数',
  'dpd8-15_settled_amount': 'DPD8-15结清金额',
  'dpd8-15_part_count': 'DPD8-15部分还款数',
  'dpd8-15_part_amount': 'DPD8-15部分还款金额',
  'dpd8-15_extend_count': 'DPD8-15展期数',
  'dpd8-15_extend_amount': 'DPD8-15展期金额',
  'dpd8-15_collection_success_amount': 'DPD8-15催回额',
  'dpd8-15_collection_success_count': 'DPD8-15催回数',
  'dpd16-30_settled_count': 'DPD16-30结清数',
  'dpd16-30_settled_amount': 'DPD16-30结清金额',
  'dpd16-30_part_count': 'DPD16-30部分还款数',
  'dpd16-30_part_amount': 'DPD16-30部分还款金额',
  'dpd16-30_extend_count': 'DPD16-30展期数',
  'dpd16-30_extend_amount': 'DPD16-30展期金额',
  'dpd16-30_collection_success_amount': 'DPD16-30催回额',
  'dpd16-30_collection_success_count': 'DPD16-30催回数',
  'dpd31_settled_count': 'DPD31+结清数',
  'dpd31_settled_amount': 'DPD31+结清金额',
  'dpd31_part_count': 'DPD31+部分还款数',
  'dpd31_part_amount': 'DPD31+部分还款金额',
  'dpd31_extend_count': 'DPD31+展期数',
  'dpd31_extend_amount': 'DPD31+展期金额',
  'dpd31_collection_success_amount': 'DPD31+催回额',
  'dpd31_collection_success_count': 'DPD31+催回数',
};

export const FieldIndex = {
  id: 'id',
  a_date: 'a_date',
  b_period_index: 'b_period_index',
  d_count: 'd_count',
  e_amount: 'e_amount',
  settled_count: 'settled_count',
  settled_amount: 'settled_amount',
  part_count: 'part_count',
  part_amount: 'part_amount',
  extend_count: 'extend_count',
  extend_amount: 'extend_amount',
  collection_success_amount: 'collection_success_amount',
  collection_success_count: 'collection_success_count',
  'dpd-3_settled_count': 'dpd-3_settled_count',
  'dpd-3_settled_amount': 'dpd-3_settled_amount',
  'dpd-3_part_count': 'dpd-3_part_count',
  'dpd-3_part_amount': 'dpd-3_part_amount',
  'dpd-3_extend_count': 'dpd-3_extend_count',
  'dpd-3_extend_amount': 'dpd-3_extend_amount',
  'dpd-3_collection_success_amount': 'dpd-3_collection_success_amount',
  'dpd-3_collection_success_count': 'dpd-3_collection_success_count',
  'dpd-2_settled_count': 'dpd-2_settled_count',
  'dpd-2_settled_amount': 'dpd-2_settled_amount',
  'dpd-2_part_count': 'dpd-2_part_count',
  'dpd-2_part_amount': 'dpd-2_part_amount',
  'dpd-2_extend_count': 'dpd-2_extend_count',
  'dpd-2_extend_amount': 'dpd-2_extend_amount',
  'dpd-2_collection_success_amount': 'dpd-2_collection_success_amount',
  'dpd-2_collection_success_count': 'dpd-2_collection_success_count',
  'dpd-1_settled_count': 'dpd-1_settled_count',
  'dpd-1_settled_amount': 'dpd-1_settled_amount',
  'dpd-1_part_count': 'dpd-1_part_count',
  'dpd-1_part_amount': 'dpd-1_part_amount',
  'dpd-1_extend_count': 'dpd-1_extend_count',
  'dpd-1_extend_amount': 'dpd-1_extend_amount',
  'dpd-1_collection_success_amount': 'dpd-1_collection_success_amount',
  'dpd-1_collection_success_count': 'dpd-1_collection_success_count',
  dpd0_settled_count: 'dpd0_settled_count',
  dpd0_settled_amount: 'dpd0_settled_amount',
  dpd0_part_count: 'dpd0_part_count',
  dpd0_part_amount: 'dpd0_part_amount',
  dpd0_extend_count: 'dpd0_extend_count',
  dpd0_extend_amount: 'dpd0_extend_amount',
  dpd0_collection_success_amount: 'dpd0_collection_success_amount',
  dpd0_collection_success_count: 'dpd0_collection_success_count',
  dpd1_settled_count: 'dpd1_settled_count',
  dpd1_settled_amount: 'dpd1_settled_amount',
  dpd1_part_count: 'dpd1_part_count',
  dpd1_part_amount: 'dpd1_part_amount',
  dpd1_extend_count: 'dpd1_extend_count',
  dpd1_extend_amount: 'dpd1_extend_amount',
  dpd1_collection_success_amount: 'dpd1_collection_success_amount',
  dpd1_collection_success_count: 'dpd1_collection_success_count',
  dpd2_settled_count: 'dpd2_settled_count',
  dpd2_settled_amount: 'dpd2_settled_amount',
  dpd2_part_count: 'dpd2_part_count',
  dpd2_part_amount: 'dpd2_part_amount',
  dpd2_extend_count: 'dpd2_extend_count',
  dpd2_extend_amount: 'dpd2_extend_amount',
  dpd2_collection_success_amount: 'dpd2_collection_success_amount',
  dpd2_collection_success_count: 'dpd2_collection_success_count',
  dpd3_settled_count: 'dpd3_settled_count',
  dpd3_settled_amount: 'dpd3_settled_amount',
  dpd3_part_count: 'dpd3_part_count',
  dpd3_part_amount: 'dpd3_part_amount',
  dpd3_extend_count: 'dpd3_extend_count',
  dpd3_extend_amount: 'dpd3_extend_amount',
  dpd3_collection_success_amount: 'dpd3_collection_success_amount',
  dpd3_collection_success_count: 'dpd3_collection_success_count',
  dpd4_settled_count: 'dpd4_settled_count',
  dpd4_settled_amount: 'dpd4_settled_amount',
  dpd4_part_count: 'dpd4_part_count',
  dpd4_part_amount: 'dpd4_part_amount',
  dpd4_extend_count: 'dpd4_extend_count',
  dpd4_extend_amount: 'dpd4_extend_amount',
  dpd4_collection_success_amount: 'dpd4_collection_success_amount',
  dpd4_collection_success_count: 'dpd4_collection_success_count',
  dpd5_settled_count: 'dpd5_settled_count',
  dpd5_settled_amount: 'dpd5_settled_amount',
  dpd5_part_count: 'dpd5_part_count',
  dpd5_part_amount: 'dpd5_part_amount',
  dpd5_extend_count: 'dpd5_extend_count',
  dpd5_extend_amount: 'dpd5_extend_amount',
  dpd5_collection_success_amount: 'dpd5_collection_success_amount',
  dpd5_collection_success_count: 'dpd5_collection_success_count',
  dpd6_settled_count: 'dpd6_settled_count',
  dpd6_settled_amount: 'dpd6_settled_amount',
  dpd6_part_count: 'dpd6_part_count',
  dpd6_part_amount: 'dpd6_part_amount',
  dpd6_extend_count: 'dpd6_extend_count',
  dpd6_extend_amount: 'dpd6_extend_amount',
  dpd6_collection_success_amount: 'dpd6_collection_success_amount',
  dpd6_collection_success_count: 'dpd6_collection_success_count',
  dpd7_settled_count: 'dpd7_settled_count',
  dpd7_settled_amount: 'dpd7_settled_amount',
  dpd7_part_count: 'dpd7_part_count',
  dpd7_part_amount: 'dpd7_part_amount',
  dpd7_extend_count: 'dpd7_extend_count',
  dpd7_extend_amount: 'dpd7_extend_amount',
  dpd7_collection_success_amount: 'dpd7_collection_success_amount',
  dpd7_collection_success_count: 'dpd7_collection_success_count',
  'dpd8-15_settled_count': 'dpd8-15_settled_count',
  'dpd8-15_settled_amount': 'dpd8-15_settled_amount',
  'dpd8-15_part_count': 'dpd8-15_part_count',
  'dpd8-15_part_amount': 'dpd8-15_part_amount',
  'dpd8-15_extend_count': 'dpd8-15_extend_count',
  'dpd8-15_extend_amount': 'dpd8-15_extend_amount',
  'dpd8-15_collection_success_amount': 'dpd8-15_collection_success_amount',
  'dpd8-15_collection_success_count': 'dpd8-15_collection_success_count',
  'dpd16-30_settled_count': 'dpd16-30_settled_count',
  'dpd16-30_settled_amount': 'dpd16-30_settled_amount',
  'dpd16-30_part_count': 'dpd16-30_part_count',
  'dpd16-30_part_amount': 'dpd16-30_part_amount',
  'dpd16-30_extend_count': 'dpd16-30_extend_count',
  'dpd16-30_extend_amount': 'dpd16-30_extend_amount',
  'dpd16-30_collection_success_amount': 'dpd16-30_collection_success_amount',
  'dpd16-30_collection_success_count': 'dpd16-30_collection_success_count',
  'dpd31_settled_count': 'dpd31_settled_count',
  'dpd31_settled_amount': 'dpd31_settled_amount',
  'dpd31_part_count': 'dpd31_part_count',
  'dpd31_part_amount': 'dpd31_part_amount',
  'dpd31_extend_count': 'dpd31_extend_count',
  'dpd31_extend_amount': 'dpd31_extend_amount',
  'dpd31_collection_success_amount': 'dpd31_collection_success_amount',
  'dpd31_collection_success_count': 'dpd31_collection_success_count',
};
export const StaticsCount = [
  'dpd-3_collection_success_count',
  'dpd-2_collection_success_count',
  'dpd-1_collection_success_count',
  'dpd1_collection_success_count',
  'dpd2_collection_success_count',
  'dpd3_collection_success_count',
  'dpd4_collection_success_count',
  'dpd5_collection_success_count',
  'dpd6_collection_success_count',
  'dpd7_collection_success_count',
  'dpd8-15_collection_success_count',
  'dpd16-30_collection_success_count',
  'dpd31_collection_success_count',
]

export const StaticsAmount = [
  'dpd-3_collection_success_amount',
  'dpd-2_collection_success_amount',
  'dpd-1_collection_success_amount',
  'dpd1_collection_success_amount',
  'dpd2_collection_success_amount',
  'dpd3_collection_success_amount',
  'dpd4_collection_success_amount',
  'dpd5_collection_success_amount',
  'dpd6_collection_success_amount',
  'dpd7_collection_success_amount',
  'dpd8-15_collection_success_amount',
  'dpd16-30_collection_success_amount',
  'dpd31_collection_success_amount',
]

export const FieldOptions2 = Object.entries(FieldLabels).slice(-124).map(([value, label]) => ({
  label,
  value,
}));

